export type BlockType = 'audio' | 'video' | 'text' | 'body' | 'image' | 'button' | 'project' | 'gallery' | 'projectGrid' | 'links' | 'quote' | 'shape' | 'emitter'
export type Animation = 'none' | 'fade' | 'rise' | 'pop'
export type LoopAnimation = 'none' | 'float' | 'spin' | 'pulse' | 'wiggle'
export type FontStyle = string
export type PageTransition = 'fade' | 'slide' | 'lift'
export type LayoutMode = 'canvas' | 'scroll'
export type Position = { x: number; y: number }
export type BackgroundType = 'color' | 'gradient' | 'image'
export type ImageFit = 'cover' | 'contain' | 'stretch' | 'repeat'
export type DeviceMode = 'desktop' | 'laptop' | 'tablet' | 'phone'
export type ResponsiveRange = 'wide' | 'medium' | 'compact'
export type ResponsiveOverrideKey = 'tablet' | 'phone'
export type CanvasAnchorX = 'left' | 'center' | 'right'
export type CanvasAnchorY = 'top' | 'center' | 'bottom'
export type ButtonVariant = 'solid' | 'soft' | 'outline' | 'text'
export type ButtonSize = 'small' | 'medium' | 'large'
export type ButtonCorner = 'sharp' | 'soft' | 'pill'
export type ButtonLinkType = 'none' | 'page' | 'url'
export type ShapeType = 'circle' | 'square' | 'rounded' | 'triangle' | 'diamond' | 'star' | 'pill'
export type ResizeCorner = 'nw' | 'ne' | 'se' | 'sw'
export type ParticleStyle = 'dots' | 'stars' | 'confetti'
export type AssetKind = 'image' | 'font'

export type ShapeResize = { id: string; type: 'shape' | 'image' | 'emitter'; corner: ResizeCorner; startX: number; startY: number; width: number; height: number; scaleX: number; scaleY: number; position: Position; centerX: boolean; centerY: boolean; anchorX?: CanvasAnchorX; anchorY?: CanvasAnchorY; left?: number; top?: number; right?: number; bottom?: number }
export type DragStartPositions = Record<string, Position>
export type Asset = { id: string; name: string; kind: AssetKind; dataUrl: string; family?: string }
export type ResponsiveOverride = { hidden?: boolean; position?: Position; width?: number; height?: number; textSize?: number; centerX?: boolean; centerY?: boolean; anchorX?: CanvasAnchorX; anchorY?: CanvasAnchorY }
export type Block = { id: string; type: BlockType; content: string; title?: string; subtitle?: string; imageUrl?: string; imageAlt?: string; imageWidth?: number; imageHeight?: number; imageBorderStyle?: 'none' | 'solid' | 'gradient'; imageBorderWidth?: number; imageBorderColor?: string; imageBorderStart?: string; imageBorderEnd?: string; imageBorderAngle?: number; imageRadius?: number; imageOpacity?: number; imageFade?: 'none' | 'top' | 'bottom' | 'left' | 'right'; emitterWidth?: number; emitterHeight?: number; fillCanvas?: boolean; particleStyle?: ParticleStyle; particleDensity?: number; animation: Animation; animationDelay?: number; animationDuration?: number; loopAnimation?: LoopAnimation; accent?: string; font?: FontStyle; textAlign?: 'left' | 'center' | 'right'; textSize?: number; textWeight?: number; textLineHeight?: number; textLetterSpacing?: number; textColor?: string; textShadowEnabled?: boolean; textShadowColor?: string; textShadowX?: number; textShadowY?: number; textShadowBlur?: number; textShadowOpacity?: number; textTransform?: 'none' | 'uppercase' | 'lowercase' | 'capitalize'; textItalic?: boolean; position?: Position; centerX?: boolean; centerY?: boolean; anchorX?: CanvasAnchorX; anchorY?: CanvasAnchorY; zIndex?: number; responsive?: Partial<Record<ResponsiveOverrideKey, ResponsiveOverride>>; buttonVariant?: ButtonVariant; buttonSize?: ButtonSize; buttonCorner?: ButtonCorner; buttonTextColor?: string; showButtonArrow?: boolean; buttonLinkType?: ButtonLinkType; buttonPageId?: string; buttonUrl?: string; shapeType?: ShapeType; shapeScale?: number; shapeWidth?: number; shapeHeight?: number }
export type PageBackground = { type: BackgroundType; color: string; gradientStart: string; gradientEnd: string; gradientAngle: number; imageUrl: string; imageFit: ImageFit }
export type Page = { id: string; name: string; slug: string; showHeader: boolean; showInNav: boolean; transition: PageTransition; layout: LayoutMode; canvasHeight?: number; background: PageBackground; blocks: Block[] }
export type Portfolio = { id: string; name: string; description: string; color: string; showPortfolioName: boolean; pages: Page[]; homePageId: string; updated: string; publishedAt?: string }
